/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * EsamiPanel.java
 *
 * Created on Nov 10, 2010, 7:02:11 PM
 */

package josteo.views;

import josteo.views.UI.TrattamentoAdvancedTableFormat;
import josteo.infrastructure.UI.PanelListBase;
import java.util.*;
import javax.swing.event.*;
import ca.odell.glazedlists.swing.*;
import ca.odell.glazedlists.*;
import ca.odell.glazedlists.gui.*;
import javax.swing.*;
import javax.swing.text.*;
import java.awt.Toolkit.*;

import josteo.viewmodels.*;
import josteo.model.paziente.*;
import josteo.application.*;
import josteo.infrastructure.helpers.*;
import josteo.infrastructure.DomainBase.*;
import josteo.infrastructure.UI.*;

import org.jdesktop.swingbinding.*;
import org.jdesktop.beansbinding.*;
import org.jdesktop.swingbinding.SwingBindings;
import javax.swing.*;
import java.awt.event.*;
import josteo.views.UI.*;
import josteo.views.UI.AnamnesiProssimaAdvancedTableFormat;
import josteo.model.tipoEsame.TipoEsame;

/**
 *
 * @author cristiano
 */
public class AnamnesiProssimePanel extends PanelListBase<AnamnesiProssima> implements IConsultoSelectedListner{
    private List<TipoEsame> _esami;

    /** Creates new form EsamiPanel */
    public AnamnesiProssimePanel() {
        super();
        initComponents();

        this._presenter = new josteo.viewmodels.AnamnesiProssimaPresenter();

        ApplicationState.getInstance().addConsultoSelectedListener(this);

        // Group the radio buttons.
        ButtonGroup group = new ButtonGroup();
        group.add(this.rbNo);
        group.add(this.rbYes);        

        this.jTable1.setRowHeight(32);

        this.rbYes.addActionListener(new RadioListener());
        this.rbNo.addActionListener(new RadioListener());
        this.taTipologia.getDocument().addDocumentListener(new UpdateListener());
        this.taLocalizzazione.getDocument().addDocumentListener(new UpdateListener());
        this.taIrradiazione.getDocument().addDocumentListener(new UpdateListener());
        this.taPeriodoInsorgenza.getDocument().addDocumentListener(new UpdateListener());
        this.taDurata.getDocument().addDocumentListener(new UpdateListener());
        this.taFamiliarita.getDocument().addDocumentListener(new UpdateListener());
        this.taAltreTerapie.getDocument().addDocumentListener(new UpdateListener());
        this.taVarie.getDocument().addDocumentListener(new UpdateListener());


        AbstractDocument pDoc=(AbstractDocument)this.taTipologia.getDocument();
        pDoc.setDocumentFilter(new DocumentSizeFilter(255));

        this._isDirty = false;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnEditing = new javax.swing.JPanel();
        pnSubmit = new javax.swing.JPanel();
        btnStore = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        spEditing = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        pnPeriodoInsorgenza = new javax.swing.JPanel();
        lblPeriodoInsorgenza = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        taPeriodoInsorgenza = new javax.swing.JTextArea();
        pnIrradiazione = new javax.swing.JPanel();
        lblIrradiazione = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        taIrradiazione = new javax.swing.JTextArea();
        pnPrimaVolta = new javax.swing.JPanel();
        lblPrimaVolta = new javax.swing.JLabel();
        rbYes = new javax.swing.JRadioButton();
        rbNo = new javax.swing.JRadioButton();
        pnDurata = new javax.swing.JPanel();
        lblDurata = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        taDurata = new javax.swing.JTextArea();
        pnTipologia = new javax.swing.JPanel();
        lblTipologia = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        taTipologia = new javax.swing.JTextArea();
        pnFamiliarita = new javax.swing.JPanel();
        lblFamiliarita = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        taFamiliarita = new javax.swing.JTextArea();
        pnLocalizzazione = new javax.swing.JPanel();
        lblLocalizzazione = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        taLocalizzazione = new javax.swing.JTextArea();
        pnVarie = new javax.swing.JPanel();
        lblVarie = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        taVarie = new javax.swing.JTextArea();
        pnAltreTerapie = new javax.swing.JPanel();
        lblAltreTerapie = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        taAltreTerapie = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(900, 350));

        pnEditing.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Anamnesi Prossima", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 2, 13))); // NOI18N

        btnStore.setText("Store");
        btnStore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStoreActionPerformed(evt);
            }
        });

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout pnSubmitLayout = new org.jdesktop.layout.GroupLayout(pnSubmit);
        pnSubmit.setLayout(pnSubmitLayout);
        pnSubmitLayout.setHorizontalGroup(
            pnSubmitLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, pnSubmitLayout.createSequentialGroup()
                .add(32, 32, 32)
                .add(btnReset)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 37, Short.MAX_VALUE)
                .add(btnStore)
                .add(34, 34, 34))
        );
        pnSubmitLayout.setVerticalGroup(
            pnSubmitLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pnSubmitLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                .add(btnStore)
                .add(btnReset))
        );

        spEditing.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        pnPeriodoInsorgenza.setPreferredSize(new java.awt.Dimension(350, 100));

        lblPeriodoInsorgenza.setText("Periodo Insorgenza");

        taPeriodoInsorgenza.setColumns(20);
        taPeriodoInsorgenza.setRows(5);
        jScrollPane2.setViewportView(taPeriodoInsorgenza);

        org.jdesktop.layout.GroupLayout pnPeriodoInsorgenzaLayout = new org.jdesktop.layout.GroupLayout(pnPeriodoInsorgenza);
        pnPeriodoInsorgenza.setLayout(pnPeriodoInsorgenzaLayout);
        pnPeriodoInsorgenzaLayout.setHorizontalGroup(
            pnPeriodoInsorgenzaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(lblPeriodoInsorgenza)
            .add(jScrollPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)
        );
        pnPeriodoInsorgenzaLayout.setVerticalGroup(
            pnPeriodoInsorgenzaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pnPeriodoInsorgenzaLayout.createSequentialGroup()
                .add(lblPeriodoInsorgenza)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );

        lblIrradiazione.setText("Irradiazione");

        taIrradiazione.setColumns(20);
        taIrradiazione.setRows(5);
        jScrollPane3.setViewportView(taIrradiazione);

        org.jdesktop.layout.GroupLayout pnIrradiazioneLayout = new org.jdesktop.layout.GroupLayout(pnIrradiazione);
        pnIrradiazione.setLayout(pnIrradiazioneLayout);
        pnIrradiazioneLayout.setHorizontalGroup(
            pnIrradiazioneLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pnIrradiazioneLayout.createSequentialGroup()
                .add(lblIrradiazione)
                .addContainerGap(331, Short.MAX_VALUE))
            .add(jScrollPane3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)
        );
        pnIrradiazioneLayout.setVerticalGroup(
            pnIrradiazioneLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pnIrradiazioneLayout.createSequentialGroup()
                .add(lblIrradiazione)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jScrollPane3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 84, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );

        lblPrimaVolta.setText("Prima Volta");

        rbYes.setText("Sì");

        rbNo.setText("No");

        org.jdesktop.layout.GroupLayout pnPrimaVoltaLayout = new org.jdesktop.layout.GroupLayout(pnPrimaVolta);
        pnPrimaVolta.setLayout(pnPrimaVoltaLayout);
        pnPrimaVoltaLayout.setHorizontalGroup(
            pnPrimaVoltaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pnPrimaVoltaLayout.createSequentialGroup()
                .add(pnPrimaVoltaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(lblPrimaVolta)
                    .add(pnPrimaVoltaLayout.createSequentialGroup()
                        .add(rbYes)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(rbNo)))
                .addContainerGap(312, Short.MAX_VALUE))
        );
        pnPrimaVoltaLayout.setVerticalGroup(
            pnPrimaVoltaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pnPrimaVoltaLayout.createSequentialGroup()
                .add(lblPrimaVolta)
                .add(0, 0, 0)
                .add(pnPrimaVoltaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(rbYes)
                    .add(rbNo)))
        );

        lblDurata.setText("Durata");

        taDurata.setColumns(20);
        taDurata.setRows(5);
        jScrollPane4.setViewportView(taDurata);

        org.jdesktop.layout.GroupLayout pnDurataLayout = new org.jdesktop.layout.GroupLayout(pnDurata);
        pnDurata.setLayout(pnDurataLayout);
        pnDurataLayout.setHorizontalGroup(
            pnDurataLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pnDurataLayout.createSequentialGroup()
                .add(lblDurata)
                .add(329, 329, 329))
            .add(jScrollPane4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)
        );
        pnDurataLayout.setVerticalGroup(
            pnDurataLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pnDurataLayout.createSequentialGroup()
                .add(lblDurata)
                .add(0, 0, 0)
                .add(jScrollPane4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 0, 0))
        );

        lblTipologia.setText("Tipologia");

        taTipologia.setColumns(20);
        taTipologia.setRows(5);
        jScrollPane5.setViewportView(taTipologia);

        org.jdesktop.layout.GroupLayout pnTipologiaLayout = new org.jdesktop.layout.GroupLayout(pnTipologia);
        pnTipologia.setLayout(pnTipologiaLayout);
        pnTipologiaLayout.setHorizontalGroup(
            pnTipologiaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pnTipologiaLayout.createSequentialGroup()
                .add(lblTipologia)
                .addContainerGap(346, Short.MAX_VALUE))
            .add(jScrollPane5, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)
        );
        pnTipologiaLayout.setVerticalGroup(
            pnTipologiaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pnTipologiaLayout.createSequentialGroup()
                .add(lblTipologia)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jScrollPane5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );

        lblFamiliarita.setText("Familiarità");

        taFamiliarita.setColumns(20);
        taFamiliarita.setRows(5);
        jScrollPane6.setViewportView(taFamiliarita);

        org.jdesktop.layout.GroupLayout pnFamiliaritaLayout = new org.jdesktop.layout.GroupLayout(pnFamiliarita);
        pnFamiliarita.setLayout(pnFamiliaritaLayout);
        pnFamiliaritaLayout.setHorizontalGroup(
            pnFamiliaritaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(lblFamiliarita)
            .add(jScrollPane6, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)
        );
        pnFamiliaritaLayout.setVerticalGroup(
            pnFamiliaritaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pnFamiliaritaLayout.createSequentialGroup()
                .add(lblFamiliarita)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jScrollPane6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );

        lblLocalizzazione.setText("Localizzazione");

        taLocalizzazione.setColumns(20);
        taLocalizzazione.setRows(5);
        jScrollPane7.setViewportView(taLocalizzazione);

        org.jdesktop.layout.GroupLayout pnLocalizzazioneLayout = new org.jdesktop.layout.GroupLayout(pnLocalizzazione);
        pnLocalizzazione.setLayout(pnLocalizzazioneLayout);
        pnLocalizzazioneLayout.setHorizontalGroup(
            pnLocalizzazioneLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pnLocalizzazioneLayout.createSequentialGroup()
                .add(lblLocalizzazione)
                .addContainerGap(313, Short.MAX_VALUE))
            .add(jScrollPane7, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)
        );
        pnLocalizzazioneLayout.setVerticalGroup(
            pnLocalizzazioneLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pnLocalizzazioneLayout.createSequentialGroup()
                .add(lblLocalizzazione)
                .add(0, 0, 0)
                .add(jScrollPane7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 0, 0))
        );

        lblVarie.setText("Varie");

        taVarie.setColumns(20);
        taVarie.setRows(5);
        jScrollPane9.setViewportView(taVarie);

        org.jdesktop.layout.GroupLayout pnVarieLayout = new org.jdesktop.layout.GroupLayout(pnVarie);
        pnVarie.setLayout(pnVarieLayout);
        pnVarieLayout.setHorizontalGroup(
            pnVarieLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pnVarieLayout.createSequentialGroup()
                .add(lblVarie)
                .add(0, 0, 0))
            .add(jScrollPane9, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)
        );
        pnVarieLayout.setVerticalGroup(
            pnVarieLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pnVarieLayout.createSequentialGroup()
                .add(lblVarie)
                .add(0, 0, 0)
                .add(jScrollPane9, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );

        lblAltreTerapie.setText("Altre Terapie");

        taAltreTerapie.setColumns(20);
        taAltreTerapie.setRows(5);
        jScrollPane8.setViewportView(taAltreTerapie);

        org.jdesktop.layout.GroupLayout pnAltreTerapieLayout = new org.jdesktop.layout.GroupLayout(pnAltreTerapie);
        pnAltreTerapie.setLayout(pnAltreTerapieLayout);
        pnAltreTerapieLayout.setHorizontalGroup(
            pnAltreTerapieLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(lblAltreTerapie)
            .add(jScrollPane8, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)
        );
        pnAltreTerapieLayout.setVerticalGroup(
            pnAltreTerapieLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pnAltreTerapieLayout.createSequentialGroup()
                .add(lblAltreTerapie)
                .add(0, 0, 0)
                .add(jScrollPane8, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pnAltreTerapie, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(pnFamiliarita, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(pnDurata, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(pnLocalizzazione, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(pnPeriodoInsorgenza, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)
            .add(pnIrradiazione, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(pnTipologia, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, pnPrimaVolta, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(pnVarie, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(pnPrimaVolta, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(5, 5, 5)
                .add(pnLocalizzazione, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(5, 5, 5)
                .add(pnIrradiazione, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(5, 5, 5)
                .add(pnTipologia, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(5, 5, 5)
                .add(pnPeriodoInsorgenza, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 108, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(5, 5, 5)
                .add(pnDurata, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(5, 5, 5)
                .add(pnFamiliarita, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(5, 5, 5)
                .add(pnAltreTerapie, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(5, 5, 5)
                .add(pnVarie, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        spEditing.setViewportView(jPanel1);

        org.jdesktop.layout.GroupLayout pnEditingLayout = new org.jdesktop.layout.GroupLayout(pnEditing);
        pnEditing.setLayout(pnEditingLayout);
        pnEditingLayout.setHorizontalGroup(
            pnEditingLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pnEditingLayout.createSequentialGroup()
                .add(87, 87, 87)
                .add(pnSubmit, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
            .add(spEditing, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE)
        );
        pnEditingLayout.setVerticalGroup(
            pnEditingLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, pnEditingLayout.createSequentialGroup()
                .add(spEditing, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(pnSubmit, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Prima Volta", "Tipologia", "Localizzazione"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 425, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(pnEditing, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
            .add(pnEditing, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnStoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStoreActionPerformed
        // TODO add your handling code here:
        store();
}//GEN-LAST:event_btnStoreActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        reset();
}//GEN-LAST:event_btnResetActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnStore;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblAltreTerapie;
    private javax.swing.JLabel lblDurata;
    private javax.swing.JLabel lblFamiliarita;
    private javax.swing.JLabel lblIrradiazione;
    private javax.swing.JLabel lblLocalizzazione;
    private javax.swing.JLabel lblPeriodoInsorgenza;
    private javax.swing.JLabel lblPrimaVolta;
    private javax.swing.JLabel lblTipologia;
    private javax.swing.JLabel lblVarie;
    private javax.swing.JPanel pnAltreTerapie;
    private javax.swing.JPanel pnDurata;
    private javax.swing.JPanel pnEditing;
    private javax.swing.JPanel pnFamiliarita;
    private javax.swing.JPanel pnIrradiazione;
    private javax.swing.JPanel pnLocalizzazione;
    private javax.swing.JPanel pnPeriodoInsorgenza;
    private javax.swing.JPanel pnPrimaVolta;
    private javax.swing.JPanel pnSubmit;
    private javax.swing.JPanel pnTipologia;
    private javax.swing.JPanel pnVarie;
    private javax.swing.JRadioButton rbNo;
    private javax.swing.JRadioButton rbYes;
    private javax.swing.JScrollPane spEditing;
    private javax.swing.JTextArea taAltreTerapie;
    private javax.swing.JTextArea taDurata;
    private javax.swing.JTextArea taFamiliarita;
    private javax.swing.JTextArea taIrradiazione;
    private javax.swing.JTextArea taLocalizzazione;
    private javax.swing.JTextArea taPeriodoInsorgenza;
    private javax.swing.JTextArea taTipologia;
    private javax.swing.JTextArea taVarie;
    // End of variables declaration//GEN-END:variables

    class AnamnesiProssimaComparator implements Comparator{
        public int compare(Object obj1, Object obj2){
            //parameter are of type Object, so we have to downcast it to Employee objects
            String dt1 = ( (AnamnesiProssima) obj1 ).get_PrimaVolta();
            String dt2 = ( (AnamnesiProssima) obj2 ).get_PrimaVolta();
            //uses compareTo method of String class to compare names of the employee
            return dt1.compareTo(dt2);
        }
    }

    class RadioListener implements ActionListener {
        public void actionPerformed(ActionEvent e) {
            AnamnesiProssimePanel.this._isDirty = true;
        }
    }

    public void ConsultoSelected( Consulto consulto ){
        System.out.println("AP->ConsultoSelected consulto.Key: " + (consulto==null? "null" : consulto.get_Key().toString()));
        this.Init();
    }

    @Override
    public void Init(){
        this._items = new SortedList( this._presenter.getItems(), new AnamnesiProssimaComparator());
        gridConfig(new AnamnesiProssimaAdvancedTableFormat());

        this._presenter.Load();

        this.addTabLisntener();

        reset();
    }



    @Override
    protected JTable getTable(){
        return this.jTable1;
    }

    @Override
    protected void bindUI(){
        AnamnesiProssima item = this._presenter.getSelected();
        if(item==null)
            item = this._presenter.getNewItem();

        System.out.println("bindUI -> selItem:"+item.get_Key().toString());
        if(item==null) return;
        boolean bBind = true;
        if(this._isDirty){
            int i = JOptionPane.showConfirmDialog(null,"Vuoi sovrascrivere i dati nel form con la nuova selezione?","Dati non salvati", JOptionPane.YES_NO_OPTION);
            bBind = (i==0);
        }
        if(bBind){
            this.rbYes.setSelected(false);
            this.rbYes.setSelected((this._presenter.getSelected()!=null)? item.get_PrimaVolta().compareTo("1")==0 : false);
            this.rbNo.setSelected(false);
            this.rbNo.setSelected((this._presenter.getSelected()!=null)? item.get_PrimaVolta().compareTo("0")==0 : false);
            this.taTipologia.setText((this._presenter.getSelected()!=null)? item.get_Tipologia() : "");
            this.taLocalizzazione.setText((this._presenter.getSelected()!=null)? item.get_Localizzazione() : "");
            this.taIrradiazione.setText((this._presenter.getSelected()!=null)? item.get_Irradiazione() : "");
            this.taPeriodoInsorgenza.setText((this._presenter.getSelected()!=null)? item.get_PeriodoInsorgenza() : "");
            this.taDurata.setText((this._presenter.getSelected()!=null)? item.get_Durata(): "");
            this.taFamiliarita.setText((this._presenter.getSelected()!=null)? item.get_Familiarita() : "");
            this.taAltreTerapie.setText((this._presenter.getSelected()!=null)? item.get_AltreTerapie() : "");
            this.taVarie.setText((this._presenter.getSelected()!=null)? item.get_Varie() : "");

            //this.taPrimaVolta.requestFocus();
            //this.spEditing.getVerticalScrollBar().setValue(0);
            //this.spEditing.getViewport().getViewportView()
            //this.lblPrimaVolta.scrollRectToVisible(new java.awt.Rectangle(0, 0, 0, 0));
            //int x=this.jPanel1.getPreferredSize().width;
            //this.spEditing.getViewport().setViewPosition(new java.awt.Point(0,0));

            //this.taPrimaVolta.setSelectionStart(0);
            //this.taPrimaVolta.setSelectionEnd(0);

            javax.swing.SwingUtilities.invokeLater(new Runnable() {
               public void run() {
                   AnamnesiProssimePanel.this.spEditing.getVerticalScrollBar().setValue(0);
               }
            });

            

            this._isDirty = false;
            System.out.println("bindUI done");
        }

    }

    @Override
    protected boolean bindToPresenter(){
        AnamnesiProssima itemTmp = new AnamnesiProssima(0
                , this.rbYes.isSelected()? "1":"0"
                , this.taTipologia.getText()
                , this.taLocalizzazione.getText()
                , this.taIrradiazione.getText()
                , this.taPeriodoInsorgenza.getText()
                , this.taDurata.getText()
                , this.taFamiliarita.getText()
                , this.taAltreTerapie.getText()
                , this.taVarie.getText()
                );
        List<BrokenRule> brokenRules = itemTmp.GetBrokenRules();
        if(brokenRules.size()>0){
            List<String> errors = new ArrayList<String>();
            for(BrokenRule br : brokenRules)
                errors.add(br.get_Message());

            JOptionPane.showMessageDialog(this, josteo.infrastructure.helpers.StringHelper.join(errors,"\n"));
            return false;
        }


        AnamnesiProssima item = this._presenter.getSelected()==null? this._presenter.getNewItem() : this._presenter.getSelected();
        System.out.println("bindToPresenter:" + item.get_Key());
        item.set_PrimaVolta(itemTmp.get_PrimaVolta());
        item.set_Tipologia(itemTmp.get_Tipologia());
        item.set_Localizzazione(itemTmp.get_Localizzazione());
        item.set_Irradiazione(itemTmp.get_Irradiazione());
        item.set_PeriodoInsorgenza(itemTmp.get_PeriodoInsorgenza());
        item.set_Durata(itemTmp.get_Durata());
        item.set_Familiarita(itemTmp.get_Familiarita());
        item.set_AltreTerapie(itemTmp.get_AltreTerapie());
        item.set_PrimaVolta(itemTmp.get_PrimaVolta());
        item.set_Varie(itemTmp.get_Varie());
        return true;
    }



}
