/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PazienteView.java
 *
 * Created on Oct 31, 2010, 12:07:49 AM
 */

package josteo.views;

import josteo.infrastructure.UI.ViewBase;
import java.util.*;

import josteo.viewmodels.PazientePresenter;
import josteo.application.ApplicationState;
import josteo.model.paziente.LkpProvincia;
import josteo.model.paziente.Paziente;
import org.jdesktop.swingbinding.*;
import org.jdesktop.beansbinding.*;
import org.jdesktop.swingbinding.SwingBindings;
import javax.swing.*;
import java.awt.event.*;
import josteo.application.*;
import josteo.infrastructure.helpers.*;

/**
 *
 * @author cristiano
 */
public class PazienteView extends ViewBase  implements josteo.infrastructure.UI.IView{

    PazientePresenter _presenter;
    List<LkpProvincia> _province;

    /** Creates new form PazienteView */
    public PazienteView() {
        super();

        initComponents();

        _province = ((IPazienteService) ContainerHelper.getContainer().getBean("PazienteService")).GetAllProvince();



        //this.cbProv.setRenderer(new LkpProvinciaRenderer());
        buildMenu();


    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtNome = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtCognome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtProfessione = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        dcDataNascita = new com.toedter.calendar.JDateChooser();
        pnAddress = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtToponimo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtCitta = new javax.swing.JTextField();
        cbProv = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        txtCap = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        txtCellulare = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtStore = new javax.swing.JButton();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("Anagrafica")));

        txtNome.setText("nome");

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 10));
        jLabel1.setText("Nome");

        txtCognome.setText("cognome");

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 10));
        jLabel2.setText("Cognome");

        txtProfessione.setText("professione");
        txtProfessione.setToolTipText("Professione");

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 10));
        jLabel3.setText("Professione");

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 10));
        jLabel4.setText("Data di Nascita");

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel1)
                            .add(txtNome, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 254, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(18, 18, 18)
                                .add(txtCognome, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE))
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(78, 78, 78)
                                .add(jLabel2))))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(dcDataNascita, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 154, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(5, 5, 5)
                                .add(jLabel4)))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel3)
                            .add(txtProfessione, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 388, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 16, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel2))
                .add(0, 0, 0)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(txtNome, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 28, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(txtCognome, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel4)
                    .add(jLabel3))
                .add(0, 0, 0)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(txtProfessione, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(dcDataNascita, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 570, 140));
        jPanel1.getAccessibleContext().setAccessibleName("Anagrafica");

        pnAddress.setBorder(javax.swing.BorderFactory.createTitledBorder("Indirizzo"));

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 10));
        jLabel5.setText("Toponimo, numero civico");

        txtToponimo.setText("toponimo, numero civico");

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 0, 10));
        jLabel6.setText("Citta'");

        txtCitta.setText("citta");

        cbProv.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 0, 10));
        jLabel7.setText("Prov");

        txtCap.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#####"))));

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 0, 10));
        jLabel8.setText("CAP");

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 0, 10));
        jLabel9.setText("Telefono");

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 0, 10));
        jLabel10.setText("Cellulare");

        jLabel11.setFont(new java.awt.Font("Lucida Grande", 0, 10));
        jLabel11.setText("Email");

        txtTelefono.setText("tel");

        txtCellulare.setText("cell");

        txtEmail.setText("email");

        org.jdesktop.layout.GroupLayout pnAddressLayout = new org.jdesktop.layout.GroupLayout(pnAddress);
        pnAddress.setLayout(pnAddressLayout);
        pnAddressLayout.setHorizontalGroup(
            pnAddressLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pnAddressLayout.createSequentialGroup()
                .add(pnAddressLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(pnAddressLayout.createSequentialGroup()
                        .addContainerGap()
                        .add(jLabel9))
                    .add(pnAddressLayout.createSequentialGroup()
                        .addContainerGap()
                        .add(jLabel11))
                    .add(pnAddressLayout.createSequentialGroup()
                        .add(5, 5, 5)
                        .add(pnAddressLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(txtEmail, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 518, Short.MAX_VALUE)
                            .add(jLabel5)
                            .add(pnAddressLayout.createSequentialGroup()
                                .add(pnAddressLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jLabel6)
                                    .add(txtCitta, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE))
                                .add(pnAddressLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(pnAddressLayout.createSequentialGroup()
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                        .add(cbProv, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 79, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                    .add(pnAddressLayout.createSequentialGroup()
                                        .add(21, 21, 21)
                                        .add(jLabel7)))
                                .add(pnAddressLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(pnAddressLayout.createSequentialGroup()
                                        .add(15, 15, 15)
                                        .add(jLabel8))
                                    .add(pnAddressLayout.createSequentialGroup()
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(txtCap, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 115, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                            .add(txtToponimo, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 518, Short.MAX_VALUE)
                            .add(pnAddressLayout.createSequentialGroup()
                                .add(txtTelefono, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 254, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(pnAddressLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jLabel10)
                                    .add(txtCellulare, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 254, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap())
        );
        pnAddressLayout.setVerticalGroup(
            pnAddressLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pnAddressLayout.createSequentialGroup()
                .add(jLabel5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 16, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 0, 0)
                .add(txtToponimo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(pnAddressLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(pnAddressLayout.createSequentialGroup()
                        .add(pnAddressLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel6)
                            .add(jLabel7))
                        .add(0, 0, 0)
                        .add(pnAddressLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(txtCitta, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(cbProv, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(txtCap, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(jLabel8))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(pnAddressLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel9)
                    .add(jLabel10))
                .add(0, 0, 0)
                .add(pnAddressLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(txtTelefono, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 28, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(txtCellulare, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 28, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel11)
                .add(0, 0, 0)
                .add(txtEmail, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 28, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(pnAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 540, 230));

        txtStore.setText("Salva");
        txtStore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStoreActionPerformed(evt);
            }
        });
        getContentPane().add(txtStore, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 200, 230, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtStoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStoreActionPerformed
        // TODO add your handling code here:
        this.bindPresenter();
        this._presenter.Store();

        ((josteo.infrastructure.UI.IView)ContainerHelper.getContainer().getBean("HomeView")).Init();
    }//GEN-LAST:event_txtStoreActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbProv;
    private com.toedter.calendar.JDateChooser dcDataNascita;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel pnAddress;
    private javax.swing.JFormattedTextField txtCap;
    private javax.swing.JTextField txtCellulare;
    private javax.swing.JTextField txtCitta;
    private javax.swing.JTextField txtCognome;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtProfessione;
    private javax.swing.JButton txtStore;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtToponimo;
    // End of variables declaration//GEN-END:variables

    public void Init(){
        Paziente p = ApplicationState.getInstance().getCurrentPaziente();
        if(p==null)
            _presenter = new PazientePresenter();
        else
            _presenter = new PazientePresenter(ApplicationState.getInstance().getCurrentPaziente());


        bindUI();
    }

    private void bindUI(){
        this.txtNome.setText(this._presenter.getNome());
        this.txtCognome.setText(this._presenter.getCognome());
        this.dcDataNascita.setDate(this._presenter.getDataNascita());
        this.txtProfessione.setText(this._presenter.getProfessione());
        this.txtToponimo.setText(this._presenter.getIndirizzo());
        this.txtCitta.setText(this._presenter.getCitta());
        this.txtCap.setText(this._presenter.getCap());
        this.txtTelefono.setText(this._presenter.getTelefono());
        this.txtCellulare.setText(this._presenter.getCellulare());
        this.txtEmail.setText(this._presenter.getEmail());


        // create the binding from List to JComboBox
        JComboBoxBinding cb = SwingBindings.createJComboBoxBinding(AutoBinding.UpdateStrategy.READ, _province, this.cbProv);
        // realize the binding
        cb.bind();

        this.cbProv.setSelectedIndex(-1);
        for(LkpProvincia p : this._province){
            if(p.getSigla().equals(this._presenter.getProv())){
                this.cbProv.setSelectedItem(p);
                break;
            }
        }     
        
    }
    
    private void bindPresenter(){
        this._presenter.setNome(this.txtNome.getText());
        this._presenter.setCognome(this.txtCognome.getText());
        this._presenter.setDataNascita(this.dcDataNascita.getDate());
        this._presenter.setProfessione(this.txtProfessione.getText());
        this._presenter.setIndirizzo(this.txtToponimo.getText());
        this._presenter.setCitta(this.txtCitta.getText());
        this._presenter.setCap(this.txtCap.getText());
        this._presenter.setTelefono(this.txtTelefono.getText());
        this._presenter.setCellulare(this.txtCellulare.getText());
        this._presenter.setEmail(this.txtEmail.getText());

        this._presenter.setProv(((LkpProvincia)this.cbProv.getSelectedItem()).getSigla());
    }

    class LkpProvinciaRenderer extends javax.swing.plaf.basic.BasicComboBoxRenderer
    {
        public java.awt.Component getListCellRendererComponent(
            JList list, Object value, int index,
            boolean isSelected, boolean cellHasFocus)
        {
            super.getListCellRendererComponent(list, value, index,
                isSelected, cellHasFocus);

            if (value != null)
            {
                LkpProvincia item = (LkpProvincia)value;
                setText( item.getSigla().toUpperCase() );
            }

            if (index == -1)
            {
                LkpProvincia item = (LkpProvincia)value;
                setText( "" + item.getSigla() );//setText( "" + item.getId() );
            }


            return this;
        }
    }

    private void buildMenu(){
        //Where the GUI is created:
        JMenuBar menuBar;
        JMenu menu, submenu;
        JMenuItem menuItem;
        JRadioButtonMenuItem rbMenuItem;
        JCheckBoxMenuItem cbMenuItem;

        //Create the menu bar.
        menuBar = new JMenuBar();

        //Build the first menu.
        menu = new JMenu("Pazienti");
        menu.setMnemonic(KeyEvent.VK_P);
        //menu.getAccessibleContext().setAccessibleDescription("The only menu in this program that has menu items");
        menuBar.add(menu);

        //a group of JMenuItems
        menuItem = new JMenuItem("Elenco Pazienti", KeyEvent.VK_H);
        //menuItem.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_1, ActionEvent.ALT_MASK));
        //menuItem.getAccessibleContext().setAccessibleDescription("This doesn't really do anything");
        menuItem.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                System.out.println(e.getID());
                josteo.application.ApplicationState.getInstance().setCurrentPaziente(null);

                josteo.application.ApplicationState.getInstance().SwitchView("HomeView");
            }
        });
        menu.add(menuItem);

        this.setJMenuBar(menuBar);
    }
}
