/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * EsamiPanel.java
 *
 * Created on Nov 10, 2010, 7:02:11 PM
 */

package josteo.views;

import josteo.views.UI.TrattamentoAdvancedTableFormat;
import josteo.infrastructure.UI.PanelListBase;
import java.util.*;
import javax.swing.event.*;
import ca.odell.glazedlists.swing.*;
import ca.odell.glazedlists.*;
import ca.odell.glazedlists.gui.*;


import josteo.viewmodels.*;
import josteo.model.paziente.*;
import josteo.application.*;
import josteo.infrastructure.helpers.*;
import josteo.infrastructure.DomainBase.*;
import josteo.infrastructure.UI.*;

import org.jdesktop.swingbinding.*;
import org.jdesktop.beansbinding.*;
import org.jdesktop.swingbinding.SwingBindings;
import javax.swing.*;
import java.awt.event.*;
import josteo.model.tipoAnamnesi.TipoAnamnesi;
import josteo.model.tipoEsame.TipoEsame;

/**
 *
 * @author cristiano
 */
public class TrattamentiPanel extends PanelListBase<Trattamento> implements IConsultoSelectedListner{

    /** Creates new form EsamiPanel */
    public TrattamentiPanel() {
        super();
        
        initComponents();

        this._presenter = new josteo.viewmodels.TrattamentiPresenter();

        ApplicationState.getInstance().addConsultoSelectedListener(this);

        this.jTable1.setRowHeight(32);

//        this.jTable1.addKeyListener(new KeyAdapter() {
//            public void keyPressed(KeyEvent e) {
//                int c = e.getKeyCode();
//                if (c == KeyEvent.VK_DELETE) {
//                    int[] index = table.getSelectedRows();
//                    e.consume();
//                    for (int i=index.length - 1; i >= 0; --i){
//                        model.removeRow(index[i]);
//                    }
//                }
//            }
//        });

        this.taDescrizione.getDocument().addDocumentListener(new UpdateListener());
        this.dcData.addPropertyChangeListener(new MyPropertyChangeListener());

        this._isDirty = false;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnEditing = new javax.swing.JPanel();
        pnData = new javax.swing.JPanel();
        dcData = new com.toedter.calendar.JDateChooser();
        lblData = new javax.swing.JLabel();
        pnDescrizione = new javax.swing.JPanel();
        lblDescrizione = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        taDescrizione = new javax.swing.JTextArea();
        pnSubmit = new javax.swing.JPanel();
        btnReset = new javax.swing.JButton();
        btnStore = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        pnEditing.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Trattamento", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 2, 13))); // NOI18N

        lblData.setText("Data");

        org.jdesktop.layout.GroupLayout pnDataLayout = new org.jdesktop.layout.GroupLayout(pnData);
        pnData.setLayout(pnDataLayout);
        pnDataLayout.setHorizontalGroup(
            pnDataLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(dcData, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 170, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .add(lblData)
        );
        pnDataLayout.setVerticalGroup(
            pnDataLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pnDataLayout.createSequentialGroup()
                .add(0, 0, 0)
                .add(lblData)
                .add(0, 0, 0)
                .add(dcData, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 0, 0))
        );

        lblDescrizione.setText("Descrizione");

        taDescrizione.setColumns(20);
        taDescrizione.setRows(5);
        jScrollPane2.setViewportView(taDescrizione);

        org.jdesktop.layout.GroupLayout pnDescrizioneLayout = new org.jdesktop.layout.GroupLayout(pnDescrizione);
        pnDescrizione.setLayout(pnDescrizioneLayout);
        pnDescrizioneLayout.setHorizontalGroup(
            pnDescrizioneLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pnDescrizioneLayout.createSequentialGroup()
                .add(lblDescrizione)
                .addContainerGap())
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jScrollPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 437, Short.MAX_VALUE)
        );
        pnDescrizioneLayout.setVerticalGroup(
            pnDescrizioneLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pnDescrizioneLayout.createSequentialGroup()
                .add(lblDescrizione)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 0, Short.MAX_VALUE)
                .add(jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 151, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 0, 0))
        );

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnStore.setText("Store");
        btnStore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStoreActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout pnSubmitLayout = new org.jdesktop.layout.GroupLayout(pnSubmit);
        pnSubmit.setLayout(pnSubmitLayout);
        pnSubmitLayout.setHorizontalGroup(
            pnSubmitLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pnSubmitLayout.createSequentialGroup()
                .addContainerGap()
                .add(btnReset)
                .add(49, 49, 49)
                .add(btnStore)
                .addContainerGap())
        );
        pnSubmitLayout.setVerticalGroup(
            pnSubmitLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pnSubmitLayout.createSequentialGroup()
                .add(0, 0, 0)
                .add(pnSubmitLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(btnStore)
                    .add(btnReset))
                .addContainerGap())
        );

        org.jdesktop.layout.GroupLayout pnEditingLayout = new org.jdesktop.layout.GroupLayout(pnEditing);
        pnEditing.setLayout(pnEditingLayout);
        pnEditingLayout.setHorizontalGroup(
            pnEditingLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pnEditingLayout.createSequentialGroup()
                .add(0, 0, 0)
                .add(pnEditingLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(pnDescrizione, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(pnData, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
            .add(pnEditingLayout.createSequentialGroup()
                .add(93, 93, 93)
                .add(pnSubmit, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(107, Short.MAX_VALUE))
        );
        pnEditingLayout.setVerticalGroup(
            pnEditingLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pnEditingLayout.createSequentialGroup()
                .add(pnData, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(10, 10, 10)
                .add(pnDescrizione, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(pnSubmit, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 27, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        jScrollPane1.setPreferredSize(new java.awt.Dimension(450, 400));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Data", "Descrizione"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 441, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(pnEditing, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(53, 53, 53))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jScrollPane1, 0, 0, Short.MAX_VALUE)
            .add(layout.createSequentialGroup()
                .add(pnEditing, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 300, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnStoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStoreActionPerformed
        // TODO add your handling code here:
        store();
}//GEN-LAST:event_btnStoreActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        reset();
}//GEN-LAST:event_btnResetActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnStore;
    private com.toedter.calendar.JDateChooser dcData;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblDescrizione;
    private javax.swing.JPanel pnData;
    private javax.swing.JPanel pnDescrizione;
    private javax.swing.JPanel pnEditing;
    private javax.swing.JPanel pnSubmit;
    private javax.swing.JTextArea taDescrizione;
    // End of variables declaration//GEN-END:variables

    class DateComparator implements Comparator{
        public int compare(Object obj1, Object obj2){
            //parameter are of type Object, so we have to downcast it to Employee objects
            Date dt1 = ( (Trattamento) obj1 ).get_Note().get_Data();
            Date dt2 = ( (Trattamento) obj2 ).get_Note().get_Data();
            //uses compareTo method of String class to compare names of the employee
            return dt1.compareTo(dt2);
        }
    }

    public void ConsultoSelected( Consulto consulto ){
        System.out.println("TrattamentiPanel->ConsultoSelected consulto.Key: " + (consulto==null? "null" : consulto.get_Key().toString()));
        this.Init();
    }

    @Override
    public void Init(){
        this._items = new SortedList( this._presenter.getItems(), new DateComparator());
        gridConfig(new TrattamentoAdvancedTableFormat());

        this._presenter.Load();

        this.addTabLisntener();

        reset();
    }



    @Override
    protected JTable getTable(){
        return this.jTable1;
    }

    @Override
    protected void bindUI(){
        Trattamento item = this._presenter.getSelected();
        if(item==null)
            item = this._presenter.getNewItem();

        System.out.println("bindUI -> selItem:"+item.get_Key().toString());
        if(item==null) return;
        boolean bBind = true;
        if(this._isDirty){
            int i = JOptionPane.showConfirmDialog(null,"Vuoi sovrascrivere i dati nel form con la nuova selezione?","Dati non salvati", JOptionPane.YES_NO_OPTION);
            bBind = (i==0);
        }
        if(bBind){
            this.taDescrizione.setText((this._presenter.getSelected()!=null)? item.get_Note().get_Descrizione() : "");
            this.dcData.setDate((this._presenter.getSelected()!=null)? item.get_Note().get_Data() : null);

            this._isDirty = false;
            System.out.println("bindUI done");
        }

    }

    @Override
    protected boolean bindToPresenter(){
        Trattamento itemTmp = new Trattamento(0
                , new josteo.model.paziente.Note(this.taDescrizione.getText(),this.dcData.getDate()));
        List<BrokenRule> brokenRules = itemTmp.GetBrokenRules();
        if(brokenRules.size()>0){
            List<String> errors = new ArrayList<String>();
            for(BrokenRule br : brokenRules)
                errors.add(br.get_Message());

            JOptionPane.showMessageDialog(this, josteo.infrastructure.helpers.StringHelper.join(errors,"\n"));
            return false;
        }


        Trattamento item = this._presenter.getSelected()==null? this._presenter.getNewItem() : this._presenter.getSelected();
        System.out.println("bindToPresenter:" + item.get_Key());
        item.set_Note(itemTmp.get_Note());
        return true;
    }



}
